const VuetifyLoaderPlugin = require('vuetify-loader/lib/plugin')

module.exports = {
  /**
   * Build configuration
   */
  build: {
    transpile: ['vuetify/lib'],
    plugins: [new VuetifyLoaderPlugin()],
    loaders: {
      stylus: {
        import: ['~assets/style/variables.styl']
      }
    },

    /**
     * You can extend webpack config here
     */
    extend(config, ctx) {
      // Run ESLint on save
      if (ctx.isDev && ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })

        // SEE: https://github.com/nuxt/nuxt.js/pull/3480#issuecomment-404150387
        config.output.globalObject = 'this'
      }

      if (ctx.isClient) {
        config.module.rules.push({
          test: /\.worker\.js$/,
          loader: 'worker-loader',
          exclude: /(node_modules)/,
          options: { outputModule: 'es6' }
        })
      }
    },

    vendor: ['chroma-js', 'highcharts', 'lodash', 'moment']
  },

  /**
   * Global CSS
   */
  css: ['~/assets/style/app.styl'],

  env: {
    apiPath: process.env.API_PATH,
    apiUri: process.env.API_URI,

    datapointsMax: 288 * 365 * 10, // 10 years of 5 minute data

    googleMapsAPIKey:
      process.env.GOOGLE_MAPS_API_KEY ||
      'AIzaSyC8zfohXmxg5VzAg9G2rCypfKmU-KpOv6k'
  },

  /**
   * Headers of the page
   */
  head: {
    title: 'Dendra',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      {
        hid: 'description',
        name: 'description',
        content:
          'Dendra is a cyberinfrastructure project for real-time sensor data storage, retrieval, management, and curation.'
      }
    ],
    link: [
      // Generated by http://www.favicomatic.com
      {
        rel: 'apple-touch-icon-precomposed',
        sizes: '57x57',
        href: '/apple-touch-icon-57x57.png'
      },
      {
        rel: 'apple-touch-icon-precomposed',
        sizes: '114x114',
        href: '/apple-touch-icon-114x114.png'
      },
      {
        rel: 'apple-touch-icon-precomposed',
        sizes: '72x72',
        href: '/apple-touch-icon-72x72.png'
      },
      {
        rel: 'apple-touch-icon-precomposed',
        sizes: '144x144',
        href: '/apple-touch-icon-144x144.png'
      },
      {
        rel: 'apple-touch-icon-precomposed',
        sizes: '60x60',
        href: '/apple-touch-icon-60x60.png'
      },
      {
        rel: 'apple-touch-icon-precomposed',
        sizes: '120x120',
        href: '/apple-touch-icon-120x120.png'
      },
      {
        rel: 'apple-touch-icon-precomposed',
        sizes: '76x76',
        href: '/apple-touch-icon-76x76.png'
      },
      {
        rel: 'apple-touch-icon-precomposed',
        sizes: '152x152',
        href: '/apple-touch-icon-152x152.png'
      },
      {
        rel: 'icon',
        type: 'image/png',
        href: '/favicon-196x196.png',
        sizes: '196x196'
      },
      {
        rel: 'icon',
        type: 'image/png',
        href: '/favicon-96x96.png',
        sizes: '96x96'
      },
      {
        rel: 'icon',
        type: 'image/png',
        href: '/favicon-32x32.png',
        sizes: '32x32'
      },
      {
        rel: 'icon',
        type: 'image/png',
        href: '/favicon-16x16.png',
        sizes: '16x16'
      },
      {
        rel: 'icon',
        type: 'image/png',
        href: '/favicon-128.png',
        sizes: '128x128'
      },
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' },

      {
        rel: 'stylesheet',
        href:
          'https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons'
      }
    ]
  },

  /**
   * Customize the progress-bar color
   */
  loading: { color: '#fff' },

  /**
   * Nuxt.js modules
   */
  modules: [],

  /**
   * Plugins to load before mounting the App
   */
  plugins: [
    { src: '~/plugins/logger', ssr: false },
    { src: '~/plugins/vuetify', ssr: false },
    { src: '~/plugins/vee-validate', ssr: false },
    { src: '~/plugins/ability', ssr: false },
    { src: '~/plugins/api', ssr: false },
    { src: '~/plugins/bus', ssr: false },
    { src: '~/plugins/date', ssr: false },
    { src: '~/plugins/maps', ssr: false },
    { src: '~/plugins/global-filters', ssr: false },
    { src: '~/plugins/global-mixin', ssr: false },
    { src: '~/plugins/web-workers', ssr: false }
  ],

  router: {
    middleware: ['auth', 'ability']
  },

  srcDir: 'src'
}
